name: Qodana
on:
  workflow_dispatch:
  pull_request_target:
  push:
    branches:
      - v4-dev

env:
  JAVA_VERSION: 21
  JAVA_DISTRIBUTION: zulu

jobs:
  qodana:
    if: ${{ !startsWith(github.head_ref, 'dependabot/') }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0  # a full history is required for pull request analysis

      # setup Gradle
      - name: Gradle Publish Release
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: ${{ env.GRADLE_VERSION }}
          arguments: assemble -i -s

      - name: 'Qodana Scan'
        # https://www.jetbrains.com/help/qodana/github.html#Usage
        uses: JetBrains/qodana-action@v2024.2
        with:
          upload-result: true
          github-token: ${{ secrets.FORLIY_ACCESS_TOKEN }}
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }} # read the steps about it below
          GITHUB_TOKEN: ${{ secrets.FORLIY_ACCESS_TOKEN }}


